// This file is hand-written, to allow boostrapping the
// quasi-peg.mjs grammar.

// It is validated in boot-env.mjs by comparing its output to
// that of the parser generated by boot-peg.mjs.

export default [
  ['todo', "this doesn't yet work"],
];
